### ISSUE TITLE
Not in opam ?

### ISSUE THREAD

**Issue by redianthus** [tokenrove/tsdl-mixer#3]
Hi,

In `README.md`, it's written: `opam install tsdl-mixer` ; but it looks like the package is not available on opam:

```sh
opam update && opam search tsdl

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org
# Existing packages for system:
tsdl        0.9.2  Thin bindings to SDL for OCaml
tsdl-image  0.1.2  SDL2_Image bindings to go with Tsdl
```

**Comment by tokenrove** [comment]
Thanks for mentioning this!  I am actually in the process of making a few updates to this and then I'll make an OPAM release.  Will close this issue once the OPAM PR is open.

**Comment by redianthus** [comment]
Great, thanks ! :) Are you going to do the same with tsdl-ttf btw ?

**Comment by tokenrove** [comment]
Yep.

**Comment by tokenrove** [comment]
Will close this if https://github.com/ocaml/opam-repository/pull/8275 gets merged.

**Comment by avsm** [comment]
Now merged into opam-repository. Sorry about the delay!

**Comment by redianthus** [comment]
Thanks to both of you!
